version: "3.3"
services:
  app:
    build:
      context: build
      dockerfile: debian/Dockerfile
    image: venatum/earnapp:debian
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./etc:/etc/earnapp
